name: Node CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: yarn install and test
        run: |
          cd ./backend
          yarn install
          yarn test
        env:
          CI: true
