name: Yarn CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: yarn install and test
        run: |
          cd ./backend
          yarn install
          yarn test
          cd ..
          cd ./frontend
          yarn test
        env:
          CI: true
